// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/garrettladley/tsks/internal/schemas"
)

type Task struct {
	ID          string             `json:"id"`
	Version     string             `json:"version"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Status      schemas.TaskStatus `json:"status"`
	CreatedAt   *string            `json:"created_at"`
	ArchivedAt  *string            `json:"archived_at"`
}
