// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/garrettladley/tsks/internal/schemas"
)

type Task struct {
	ID          string             `json:"id"`
	Version     time.Time          `json:"version"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Status      schemas.TaskStatus `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	ArchivedAt  *time.Time         `json:"archived_at"`
}
