// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  id, title, description, status
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, version, title, description, status, created_at, archived_at
`

type CreateTaskParams struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Status      string  `json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks
SET archived_at = CURRENT_TIMESTAMP
WHERE (id, version) IN (
  SELECT t1.id, MAX(t1.version)
  FROM tasks t1
  WHERE t1.id = ?
  GROUP BY t1.id
)
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, version, title, description, status, created_at, archived_at FROM tasks t1
WHERE t1.id = ?
  AND t1.archived_at IS NULL
  AND t1.version = (SELECT MAX(t2.version) FROM tasks t2 WHERE t2.id = ?)
LIMIT 1
`

type GetTaskParams struct {
	ID   string `json:"id"`
	ID_2 string `json:"id_2"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.ID, arg.ID_2)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT t1.id, t1.version, t1.title, t1.description, t1.status, t1.created_at, t1.archived_at FROM tasks t1
INNER JOIN (
    SELECT id, MAX(version) as max_version
    FROM tasks
    GROUP BY id
) t2 ON t1.id = t2.id AND t1.version = t2.max_version
WHERE t1.archived_at IS NULL
ORDER BY t1.created_at DESC, t1.version DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
INSERT INTO tasks (
  id, title, description, status
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, version, title, description, status, created_at, archived_at
`

type UpdateTaskParams struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Status      string  `json:"status"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
